### ISSUE TITLE
Create enough of the GUI to allow a user to select the size of a rectangle.

### ISSUE THREAD

**Issue by Darrah** [beloitcollegecomputerscience/Sona-Drawing#1]

**Comment by Darrah** [comment]
First GUI team meeting scheduled.

**Comment by Darrah** [comment]
Simon is working on code to specify rectangle sizes.

**Comment by REN-aissance** [comment]
This is probably fixed in #20 
Added two sliders that allow the user to select the canvas/grid/mesh size

**Comment by Darrah** [comment]
GUI in place. Need to interface with the rest of the project.
