### ISSUE TITLE
When user clicks a location on the screen, decide how to add dots in the nearest "acceptable" grid locations.

### ISSUE THREAD

**Issue by Darrah** [beloitcollegecomputerscience/Sona-Drawing#8]

**Comment by Darrah** [comment]
The team believes the code is complete, but being debugged.

**Comment by Abhi183** [comment]
Just finished, function is called closestpoint. It is in the dotsposition file. Soon to be commited.

**Comment by Darrah** [comment]
Code merged. Apparently complete.
